# Generated by Django 5.2 on 2025-05-28 20:39

import datetime

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        max_length=150,
                        null=True,
                        verbose_name="Место для выполнения привычки",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="введите время в формате чч:мм",
                        null=True,
                        verbose_name="желаемое время",
                    ),
                ),
                ("move", models.CharField(max_length=150, verbose_name="Привычка")),
                (
                    "good_hab",
                    models.BooleanField(
                        default=False, help_text="Признак приятной привычки"
                    ),
                ),
                (
                    "periodicity",
                    models.IntegerField(
                        default=1,
                        help_text="Введите число от 1 до 7, где 1 - ежедневное выполнение, а 7 - еженедельное",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(7),
                        ],
                        verbose_name="Периодичность (в днях)",
                    ),
                ),
                (
                    "reward",
                    models.TextField(
                        verbose_name="Вознаграждение за выполнение привычки"
                    ),
                ),
                (
                    "execution_time",
                    models.DurationField(
                        blank=True,
                        help_text="Формат: ЧЧ:ММ:СС (например, 00:02:00 — 2 минуты)",
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(
                                limit_value=datetime.timedelta(seconds=120)
                            )
                        ],
                        verbose_name="Время на выполнение",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "linked_hab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="habbits.habits",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "привычка",
                "verbose_name_plural": "привычки",
            },
        ),
    ]
