# Generated by Django 5.2 on 2025-05-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habbits", "0003_alter_habits_linked_hab_alter_habits_periodicity"),
    ]

    operations = [
        migrations.AddField(
            model_name="habits",
            name="last_remember",
            field=models.DateTimeField(
                blank=True,
                help_text="Когда в последний раз было отправлено напоминание",
                null=True,
                verbose_name="Последнее напоминание",
            ),
        ),
    ]
