# Generated by Django 5.2 on 2025-05-30 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habbits', '0004_habits_last_remember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habits',
            name='reward',
            field=models.TextField(blank=True, null=True, verbose_name='Вознаграждение за выполнение привычки'),
        ),
    ]
