# Generated by Django 5.2 on 2025-05-28 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_id",
            field=models.CharField(
                default="00000000", unique=True, verbose_name="Телеграм id"
            ),
        ),
    ]
